@AuthService_HostAddress = http://localhost:5064

POST {{AuthService_HostAddress}}/api/auth/login
Accept: application/json
Content-Type: application/json
{
  "username": "admin",
  "password": "admin123"
}

###
